DROP TABLE TIMETABLE IF EXISTS;
DROP TABLE RECORD_PROJECT IF EXISTS;
DROP TABLE RECORD_EMPLOYEE IF EXISTS;
DROP TABLE RECORD IF EXISTS;
DROP TABLE PROJECT IF EXISTS;
DROP TABLE EMPLOYEE IF EXISTS;
DROP TABLE USER IF EXISTS;
