CREATE TABLE
    USER
    (
        USERNAME VARCHAR(25) NOT NULL PRIMARY KEY,
        PASSWORD VARCHAR(25) NOT NULL,
        NAME VARCHAR(25) NOT NULL
    );
CREATE TABLE
    EMPLOYEE
    (
        ID IDENTITY NOT NULL PRIMARY KEY,
        EMPLOYEE_NAME VARCHAR(255) NOT NULL,
        KIND VARCHAR(255) NOT NULL,
        SALARY DECIMAL(10,2) NOT NULL
    );
CREATE TABLE
    PROJECT
    (
        ID IDENTITY NOT NULL PRIMARY KEY,
        PROJECT_NAME VARCHAR(255) NOT NULL
    );
CREATE TABLE
    RECORD
    (
        ID IDENTITY NOT NULL PRIMARY KEY,
        TYPE_CODE VARCHAR(255) NOT NULL,
        RECORD_DATE TIMESTAMP(2) DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONTENT CLOB NOT NULL
    );
CREATE TABLE
    RECORD_EMPLOYEE
    (
        EMPLOYEE_ID INTEGER NOT NULL,
        RECORD_ID INTEGER NOT NULL,
        PRIMARY KEY(EMPLOYEE_ID, RECORD_ID),
        FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
        FOREIGN KEY (RECORD_ID) REFERENCES RECORD(ID)
    );
CREATE TABLE
    RECORD_PROJECT
    (
        PROJECT_ID INTEGER NOT NULL,
        RECORD_ID INTEGER NOT NULL,
        PRIMARY KEY(PROJECT_ID, RECORD_ID),
        FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID),
        FOREIGN KEY (RECORD_ID) REFERENCES RECORD(ID)
    );   
CREATE TABLE
    TIMETABLE
    (
        ID IDENTITY NOT NULL PRIMARY KEY,
        EMPLOYEE_ID INTEGER NOT NULL,
        PROJECT_ID INTEGER NOT NULL,
        START_DATE TIMESTAMP(2) NOT NULL,
        END_DATE TIMESTAMP(2) NOT NULL,
        FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
        FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
    );