INSERT INTO user (username, password, name) VALUES ('nortal', 'qwerty', 'Nortal Developer');
INSERT INTO user (username, password, name) VALUES ('benson', 'qwerty', 'Benson');

INSERT INTO EMPLOYEE (employee_name, kind, salary) VALUES ('Rigby', 'Raccoon', 500);
INSERT INTO EMPLOYEE (employee_name, kind, salary) VALUES ('Mordecai', 'Blue jay', 500);
INSERT INTO EMPLOYEE (employee_name, kind, salary) VALUES ('Hi-Five Ghost', 'Ghost', 500)
INSERT INTO EMPLOYEE (employee_name, kind, salary) VALUES ('Muscle Man', 'Man', 500);

INSERT INTO PROJECT (PROJECT_NAME) VALUES ('Wash the car');
INSERT INTO PROJECT (PROJECT_NAME) VALUES ('Organize a party');

INSERT INTO RECORD (TYPE_CODE, RECORD_DATE, CONTENT) VALUES ('POSITIVE', CURRENT_TIMESTAMP - '1' DAY, 'Added wax and did not slack a lot.');
INSERT INTO RECORD (TYPE_CODE, RECORD_DATE, CONTENT) VALUES ('NEUTRAL', CURRENT_TIMESTAMP - '1' DAY, 'Party Pete was not there');

INSERT INTO RECORD_EMPLOYEE (EMPLOYEE_ID, RECORD_ID) VALUES (0,0);
INSERT INTO RECORD_EMPLOYEE (EMPLOYEE_ID, RECORD_ID) VALUES (1,0);
INSERT INTO RECORD_PROJECT (PROJECT_ID, RECORD_ID) VALUES (0,0);

INSERT INTO RECORD_EMPLOYEE (EMPLOYEE_ID, RECORD_ID) VALUES (2,1);
INSERT INTO RECORD_EMPLOYEE (EMPLOYEE_ID, RECORD_ID)VALUES (3,1);
INSERT INTO RECORD_PROJECT (PROJECT_ID, RECORD_ID) VALUES (1,1);

INSERT INTO TIMETABLE (EMPLOYEE_ID, PROJECT_ID, START_DATE, END_DATE) VALUES (0, 0, CURRENT_TIMESTAMP - '10' DAY, CURRENT_TIMESTAMP - '3' DAY);
INSERT INTO TIMETABLE (EMPLOYEE_ID, PROJECT_ID, START_DATE, END_DATE) VALUES (1, 0, CURRENT_TIMESTAMP - '8' DAY, CURRENT_TIMESTAMP - '2' DAY);
INSERT INTO TIMETABLE (EMPLOYEE_ID, PROJECT_ID, START_DATE, END_DATE) VALUES (0, 0, CURRENT_TIMESTAMP - '6' DAY, CURRENT_TIMESTAMP - '1' DAY);
INSERT INTO TIMETABLE (EMPLOYEE_ID, PROJECT_ID, START_DATE, END_DATE) VALUES (0, 1, CURRENT_TIMESTAMP - '5' DAY, CURRENT_TIMESTAMP);
INSERT INTO TIMETABLE (EMPLOYEE_ID, PROJECT_ID, START_DATE, END_DATE) VALUES (1, 1, CURRENT_TIMESTAMP - '4' DAY, CURRENT_TIMESTAMP - '1' DAY);
INSERT INTO TIMETABLE (EMPLOYEE_ID, PROJECT_ID, START_DATE, END_DATE) VALUES (1, 1, CURRENT_TIMESTAMP - '3' DAY, CURRENT_TIMESTAMP);
